// CrewBus M5 Mobile Theme Tokens & Styles
// Cohesive with Desktop Linear/Raycast Dark Studio design.
export const THEME = Object.freeze({
  bg: '#090a0f',
  card: '#12151f',
  cardElevated: '#171b29',
  border: '#1e2235',
  borderFocus: '#383f60',
  primary: '#6366f1',
  primaryLight: '#818cf8',
  emerald: '#10b981',
  emeraldMuted: 'rgba(16, 185, 129, 0.15)',
  amber: '#f59e0b',
  amberMuted: 'rgba(245, 158, 11, 0.15)',
  rose: '#f43f5e',
  roseMuted: 'rgba(244, 63, 94, 0.15)',
  text: '#f1f5f9',
  textMuted: '#94a3b8',
  textSubtle: '#64748b',
  textDim: '#475569',
});

export const STYLES = {
  screen: { flex: 1, backgroundColor: THEME.bg },
  body: { flex: 1, padding: 14, gap: 10 },
  card: {
    backgroundColor: THEME.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.border,
    padding: 12,
    gap: 8,
  },
  cardTitle: { color: THEME.text, fontSize: 14, fontWeight: '700' },
  cardSub: { color: THEME.textMuted, fontSize: 12, lineHeight: 17 },
  text: { color: THEME.text, fontSize: 13 },
  textMuted: { color: THEME.textMuted, fontSize: 12 },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 99,
    alignSelf: 'flex-start',
  },
  input: {
    backgroundColor: THEME.cardElevated,
    borderWidth: 1,
    borderColor: THEME.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    color: THEME.text,
    fontSize: 13,
  },
  btnPrimary: {
    backgroundColor: THEME.primary,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSecondary: {
    backgroundColor: THEME.cardElevated,
    borderWidth: 1,
    borderColor: THEME.border,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnDanger: {
    backgroundColor: THEME.roseMuted,
    borderWidth: 1,
    borderColor: THEME.rose,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSuccess: {
    backgroundColor: THEME.emeraldMuted,
    borderWidth: 1,
    borderColor: THEME.emerald,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: { color: THEME.text, fontSize: 13, fontWeight: '600' },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
};
