// CrewBus M4 desktop static self-check (`npm test` inside apps/desktop).
// No dependencies, no network: every JSON parses, every cross-referenced
// path exists. Fails non-zero with the first missing piece.
// Run: `node scripts/check.mjs` (from apps/desktop/) or `npm test`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const desktop = path.resolve(here, '..');
const repo = path.resolve(desktop, '..', '..');

let failures = 0;
function ok(cond, label) {
  console.log((cond ? 'ok   ' : 'FAIL ') + label);
  if (!cond) failures += 1;
}
function isFile(p) {
  try {
    return fs.statSync(p).isFile();
  } catch {
    return false;
  }
}
function parseJson(rel) {
  const abs = path.join(desktop, rel);
  try {
    JSON.parse(fs.readFileSync(abs, 'utf8'));
    ok(true, 'parses: ' + rel);
    return true;
  } catch (e) {
    ok(false, 'parses: ' + rel + ' (' + String((e && e.message) || e) + ')');
    return false;
  }
}

// 1. Every JSON file parses.
['package.json', 'src-tauri/tauri.conf.json', 'src-tauri/capabilities/main.json'].forEach(parseJson);

// 2. Cross-referenced paths exist.
const conf = JSON.parse(fs.readFileSync(path.join(desktop, 'src-tauri', 'tauri.conf.json'), 'utf8'));
const cap = JSON.parse(fs.readFileSync(path.join(desktop, 'src-tauri', 'capabilities', 'main.json'), 'utf8'));
ok(
  isFile(path.resolve(desktop, 'src-tauri', conf.build.frontendDist, 'index.html')),
  'tauri.conf frontendDist -> src/index.html exists'
);
for (const w of conf.app.windows || []) {
  ok(isFile(path.join(desktop, 'src-tauri', conf.build.frontendDist, w.url)), 'window "' + w.label + '" url -> src/' + w.url);
}
ok(
  Array.isArray(cap.windows) && cap.windows.every((l) => (conf.app.windows || []).some((w) => w.label === l)),
  'capability windows are all declared in tauri.conf.json'
);
['src/index.html', 'src/main.js', 'src/pair.html', 'src/pair.js', 'scripts/check.mjs', 'README.md',
  'src-tauri/Cargo.toml', 'src-tauri/src/main.rs',
  'src/vendor/runtime/index.js', 'src/vendor/runtime/auth.js', 'src/vendor/runtime/routes.js',
  'src/vendor/runtime/supervisor.js', 'src/vendor/runtime/cache.js',
  'src/vendor/contracts/pairing.json'].forEach((rel) => ok(isFile(path.join(desktop, rel)), 'exists: ' + rel));

// Sidecar target + contract/runtime references the scaffold is built against.
ok(isFile(path.join(repo, 'bin', 'crewbus.js')), 'sidecar entry exists: bin/crewbus.js');
ok(isFile(path.join(repo, 'packages', 'client-runtime', 'index.js')), 'client-runtime exists: packages/client-runtime/index.js');
ok(isFile(path.join(repo, 'packages', 'contracts', 'pairing.json')), 'pairing contract exists: packages/contracts/pairing.json');
ok(isFile(path.join(repo, 'docs', 'DESKTOP_SPIKE.md')), 'decision record exists: docs/DESKTOP_SPIKE.md');

// Capability hygiene: no fs scope, no remote allowance. Frontend fetch is
// browser-native (no http plugin), fenced by the CSP connect-src below.
const permIds = (cap.permissions || []).map((p) => (typeof p === 'string' ? p : p.identifier));
ok(!permIds.some((id) => String(id).startsWith('fs:')), 'no fs capability granted');
ok(!permIds.some((id) => String(id).startsWith('http:')), 'no http plugin capability (would need tauri-plugin-http; fetch is browser-native)');
const csp = String((conf.app && conf.app.security && conf.app.security.csp) || '');
ok(csp.includes('http://127.0.0.1:*') && csp.includes('http://localhost:*') && !csp.match(/https?:\/\/(?!127\.0\.0\.1|localhost)[\w.-]+/), 'CSP connect-src is loopback-only');
ok(!JSON.stringify(cap).match(/https?:\/\/(?!127\.0\.0\.1|localhost)[\w.-]+/), 'no remote URL in capabilities');

// Vendored runtime (scripts/vendor-runtime.mjs): the Tauri static shell
// serves src/ only, so src/*.js must never import out of root.
const read = (rel) => fs.readFileSync(path.join(desktop, rel), 'utf8');
for (const f of ['index.js', 'auth.js', 'routes.js', 'supervisor.js', 'cache.js']) {
  const upstream = fs.readFileSync(path.join(repo, 'packages', 'client-runtime', f), 'utf8');
  ok(read(`src/vendor/runtime/${f}`).endsWith(upstream), `vendored ${f} matches packages/client-runtime/${f} (plus header)`);
}
ok(read('src/vendor/runtime/index.js').includes('DO NOT EDIT — generated by scripts/vendor-runtime.mjs'), 'vendor header present');
const vendorContract = JSON.parse(read('src/vendor/contracts/pairing.json'));
const pairingScopes = JSON.parse(fs.readFileSync(path.join(repo, 'packages', 'contracts', 'pairing.json'), 'utf8')).scopes;
ok(JSON.stringify([...vendorContract.scopes].sort()) === JSON.stringify([...pairingScopes].sort()), 'vendored contract matches packages/contracts/pairing.json');
for (const rel of ['src/main.js', 'src/pair.js']) {
  ok(read(rel).includes('./vendor/runtime/'), `${rel} imports the vendored runtime`);
  ok(!/(from\s+|import\s*\()\s*['"]\.{1,2}\/[^'"]*packages\/client-runtime\//.test(read(rel)), `${rel} has no out-of-root runtime imports`);
}
ok(read('src/main.js').includes('allowLoopback') && read('src/main.js').includes('Supervisor'), 'main.js wires Supervisor (desktop-sidecar allowLoopback)');
ok(read('src/pair.js').includes('parsePairUrl'), 'pair.js validates via the runtime parsePairUrl');

// 3. Normie-release wiring: bundled node + shipped core + inert updater.
// (Static only — no network, no toolchain. The first real compile happens in
// CI via .github/workflows/release-desktop.yml after fetch-node.mjs stages
// per-platform node binaries into src-tauri/binaries/.)
const mainRsRel = read('src-tauri/src/main.rs');
ok(isFile(path.join(desktop, 'scripts', 'fetch-node.mjs')), 'exists: scripts/fetch-node.mjs (build-time node vendor)');
ok(isFile(path.join(desktop, 'src-tauri', 'build.rs')), 'exists: src-tauri/build.rs (tauri_build::build for generate_context!)');
ok(isFile(path.join(desktop, 'RELEASE.md')), 'exists: RELEASE.md (maintainer signing/tag steps)');
ok(isFile(path.join(repo, '.github', 'workflows', 'release-desktop.yml')), 'exists: .github/workflows/release-desktop.yml (desktop-v* tags only)');
ok(read('src-tauri/build.rs').includes('tauri_build::build()'), 'build.rs calls tauri_build::build()');
const extBin = conf.bundle.externalBin || [];
ok(Array.isArray(extBin) && extBin.includes('binaries/node'), 'tauri.conf externalBin packs the per-platform node sidecar');
const resources = conf.bundle.resources || [];
ok(Array.isArray(resources) && resources.some((r) => String(r).includes('bin')), 'tauri.conf resources ship the crewbus core (bin/crewbus.js + bin/lib)');
ok(conf.bundle.createUpdaterArtifacts === true, 'tauri.conf createUpdaterArtifacts ON (signing live: tag builds emit signed updater bundles)');
const bundleIcons = conf.bundle.icon || [];
for (const f of ['icons/32x32.png', 'icons/128x128.png', 'icons/256x256.png', 'icons/512x512.png', 'icons/icon.icns', 'icons/icon.ico']) {
  ok(bundleIcons.includes(f) && isFile(path.join(desktop, 'src-tauri', f)), `bundle icon listed + present: ${f}`);
}
ok(conf.productName === 'CrewBus', 'productName stays "CrewBus" for the installer');
ok(
  conf.bundle.windows && conf.bundle.windows.nsis && conf.bundle.windows.nsis.installMode === 'currentUser',
  'NSIS installMode is currentUser (per-user default, no admin prompt for normies)',
);
const updater = (conf.plugins && conf.plugins.updater) || {};
ok(updater.active === true, 'updater active in config (inert until signing keys land)');
ok(
  Array.isArray(updater.endpoints) && updater.endpoints.some((u) => String(u).startsWith('https://github.com/') && String(u).endsWith('/latest.json')),
  'updater endpoint points at a GitHub Releases latest.json template',
);
ok(typeof updater.pubkey === 'string', 'updater pubkey key present (empty until a maintainer adds the signing key)');
ok(typeof updater.pubkey === 'string' && updater.pubkey.length > 0, 'updater pubkey is a non-empty string (signing live)');
const spawnPerms = (cap.permissions || []).filter((p) => typeof p !== 'string' && String(p.identifier).startsWith('shell:'));
const spawnScope = spawnPerms.find((p) => p.identifier === 'shell:allow-spawn');
ok(
  !!(spawnScope && (spawnScope.allow || []).some((a) => a.name === 'node')),
  'capabilities shell:allow-spawn grants the bundled "node" sidecar',
);
ok(!permIds.includes('shell:allow-execute'), 'no PATH-fallback execute scope (sidecar-only: Command::new is private in shell v2)');
for (const p of spawnPerms) {
  for (const a of p.allow || []) {
    const args = a.args || [];
    ok(args.includes('serve') && args.includes('--port') && args.includes('0'), `shell scope "${a.name}" stays pinned to serve --port 0`);
  }
}
const cargo2 = read('src-tauri/Cargo.toml');
ok(cargo2.includes('tauri-plugin-updater'), 'Cargo: tauri-plugin-updater declared (inert: no check() call at startup)');
ok(mainRsRel.includes('resolve_crewbus_js'), 'main.rs resolves the shipped core via resource_dir()');
ok(mainRsRel.includes('resource_dir()'), 'main.rs uses the documented path().resource_dir() pattern');
ok(mainRsRel.includes('sidecar("node")'), 'main.rs uses the bundled node sidecar');
ok(!mainRsRel.includes('Command::new("node")'), 'main.rs has no system-PATH fallback (private API in shell v2)');
ok(mainRsRel.includes('"serve", "--port", "0"'), 'main.rs keeps the --port 0 pinning');
ok(mainRsRel.includes('first_loopback_url'), 'main.rs keeps the stdout port-parse exactly as-is');
ok(mainRsRel.includes('dashboard-ready'), 'main.rs keeps the dashboard-ready emit');
ok(mainRsRel.includes('tauri_plugin_updater::Builder::new().build()'), 'main.rs registers the updater plugin (no startup check call)');
ok(!/\.check\(\)\.await/.test(mainRsRel), 'main.rs never auto-checks for updates at startup (inert without keys)');

// Tauri plugins declared, not TODO: single-instance + autostart.
const cargo = read('src-tauri/Cargo.toml');
ok(cargo.includes('tauri-plugin-single-instance'), 'Cargo: tauri-plugin-single-instance declared');
ok(cargo.includes('tauri-plugin-autostart'), 'Cargo: tauri-plugin-autostart declared');
const mainRs = read('src-tauri/src/main.rs');
ok(mainRsRel.includes('tauri_plugin_single_instance::init'), 'main.rs inits single-instance (second launch focuses, never double-sidecars)');
ok(mainRsRel.includes('tauri_plugin_autostart::init'), 'main.rs inits autostart (start-minimized-friendly)');
ok(mainRsRel.includes('npm run tauri build'), 'main.rs comments the toolchain verify command');
ok(permIds.includes('autostart:allow-enable') && permIds.includes('autostart:allow-disable') && permIds.includes('autostart:allow-is-enabled'), 'capabilities grant the documented autostart permissions');

if (failures > 0) {
  console.error(failures + ' check(s) FAILED');
  process.exit(1);
}
console.log('desktop spike scaffold: all checks passed');
