// CrewBus M4 desktop shell — static ES module (no bundler yet).
// Shared runtime is VENDORED (src/vendor/runtime/, generated by
// `npm run vendor` from packages/client-runtime — never import out of
// root): Supervisor (single retry owner, allowLoopback:true — the desktop
// sidecar IS the loopback exception; mobile never passes this),
// walkRoutes over known URLs, the canonical isLoopbackUrl gate, and the
// device auth store (memory default; OS-keychain binding is a toolchain
// TODO below). Until the bundler lands it also runs as plain static JS:
// browser globals only, `node --check` clean.
//
// Dashboard URL resolution order:
//   1. `?dashboard=http://127.0.0.1:PORT` query param (dev / tests), else
//   2. Tauri `dashboard-ready` event { url } from the Rust supervisor, else
//   3. manual entry in the status line (dev without Tauri).
// Only loopback URLs are ever accepted (spec: no silent loopback fallback
// means we ALSO never silently accept a non-loopback sidecar URL).

'use strict';

import { Supervisor, walkRoutes, isLoopbackUrl, createAuthStore, createMemorySecureStore } from './vendor/runtime/index.js';

var frame = document.getElementById('dashboard');
var dot = document.getElementById('conn-dot');
var statusEl = document.getElementById('status');
var urlEl = document.getElementById('sidecar-url');
var localEnv = document.getElementById('local-env');
var pairBtn = document.getElementById('pair-open');

var dashboardUrl = null;
var pollTimer = null;

// Single retry owner for the sidecar transport (route-walk on every
// attempt, jittered backoff, foreground retryNow). allowLoopback:true is
// desktop-sidecar-only — the sidecar IS 127.0.0.1 by construction.
var supervisor = new Supervisor({
  probe: function (route) { return probeBoard(route); },
  getRoutes: function () { return dashboardUrl ? [dashboardUrl] : []; },
  allowLoopback: true,
});

// Device credential store: memory default in this static shell.
// TODO(toolchain): bind the OS keychain adapter here before packaging
// (and pin the scope vocabulary via createAuthStore({ knownScopes }) if
// the contract file ever stops resolving); never persist abd-… to
// localStorage. Exposed for the pair window / toolchain bridge.
var deviceStore = createAuthStore({ secureStore: createMemorySecureStore() });
if (typeof window !== 'undefined') window.__crewbusDeviceStore = deviceStore;

function say(t) {
  if (statusEl) {
    statusEl.textContent = t;
    if (t && t.indexOf('sidecar live at') === 0) {
      statusEl.style.display = 'none';
      if (frame) frame.style.height = 'calc(100vh - 38px)';
    } else {
      statusEl.style.display = 'block';
      if (frame) frame.style.height = 'calc(100vh - 66px)';
    }
  }
}

function markConn(ok, detail) {
  if (!dot) return;
  dot.style.color = ok ? '#38d39f' : '#f85149';
  dot.title = (ok ? 'connected: ' : 'unreachable: ') + (detail || '');
}

function apiBase() {
  return dashboardUrl ? dashboardUrl.replace(/\/+$/, '') : null;
}

function stopPoll() {
  if (pollTimer !== null) {
    clearInterval(pollTimer);
    pollTimer = null;
  }
}

function pollOnce() {
  var base = apiBase();
  if (!base) return;
  probeBoard(base).then(function (ok) {
    if (ok) {
      markConn(true, 'last poll ok');
      say('sidecar live at ' + base + ' — dashboard below is the sidecar\u2019s own UI.');
      if (supervisor.getState().state !== 'connected') supervisor.retryNow().catch(function () {});
    } else {
      markConn(false, 'board poll failed');
      say('sidecar unreachable at ' + base + ' (GET /api/board failed).');
      supervisor.noteDrop('board poll failed');
    }
  });
}

// Silent boolean probe shared by the Supervisor and walkRoutes (UI updates
// stay in pollOnce so route-walks never flicker the status line).
function probeBoard(route) {
  var base = String(route).replace(/\/+$/, '');
  return fetch(base + '/api/board', { cache: 'no-store' }).then(function (r) {
    if (r.ok) return true;
    return fetch(base + '/healthz', { cache: 'no-store' }).then(function (r2) { return r2.ok; }).catch(function () { return false; });
  }).catch(function () {
    return fetch(base + '/healthz', { cache: 'no-store' }).then(function (r2) { return r2.ok; }).catch(function () { return false; });
  });
}

function setDashboardUrl(u, why) {
  if (!isLoopbackUrl(u)) {
    say('refused non-loopback sidecar URL (' + why + '): ' + u);
    return;
  }
  var clean = u.replace(/\/+$/, '');
  // First-that-works over the known URL (today one candidate; the walk is
  // the seam multi-route hints will plug into), loopback-only by gate above.
  walkRoutes([clean], probeBoard, { allowLoopback: true }).then(function (won) {
    if (!won.ok) {
      say('sidecar unreachable at ' + clean + ' (' + (won.reason || 'no route') + ').');
      return;
    }
    dashboardUrl = won.route.replace(/\/+$/, '');
    if (urlEl) urlEl.textContent = dashboardUrl.replace(/^http:\/\//, '');
    if (frame) frame.src = dashboardUrl + '/';
    supervisor.updateRoutes([dashboardUrl]);
    stopPoll();
    pollOnce();
    pollTimer = setInterval(pollOnce, 5000);
    supervisor.retryNow().catch(function () {});
  });
}

// 1. dev/test override: ?dashboard=http://127.0.0.1:PORT
try {
  var q = new URLSearchParams(window.location.search).get('dashboard');
  if (q) setDashboardUrl(q, 'query param');
} catch (_) { /* location may be opaque in some webviews */ }

// 2. Tauri supervisor event (present only under `tauri dev` / built app).
// The Tauri JS API itself is wired on the toolchain machine (npm install);
// the dynamic feature-detect below keeps this file runnable as plain
// static HTML until then. Runtime imports above are vendored in-repo, so
// they need no install (`node --check` clean).
if (window.__TAURI__ && window.__TAURI__.event && typeof window.__TAURI__.event.listen === 'function') {
  window.__TAURI__.event.listen('dashboard-ready', function (ev) {
    var u = ev && ev.payload && ev.payload.url;
    if (u) setDashboardUrl(String(u), 'supervisor event');
  });
  window.__TAURI__.event.listen('dashboard-stopped', function () {
    stopPoll();
    supervisor.noteDrop('sidecar stopped');
    markConn(false, 'sidecar stopped');
    say('sidecar stopped (remote-only mode). Board state untouched — nothing was deleted.');
  });
  window.__TAURI__.event.listen('dashboard-error', function (ev) {
    stopPoll();
    supervisor.noteDrop('sidecar error');
    markConn(false, 'sidecar error');
    var msg = ev && ev.payload && (ev.payload.message || ev.payload);
    say('sidecar failed: ' + msg + ' — board untouched. Restart the app; if it repeats, run the sidecar by hand: node <core> serve --port 0 --board <app-data>/board');
  });
}

// 2b. Race-proof catch-up: the backend may emit dashboard-ready/error
// BEFORE this webview loads (setup spawns at boot). Query sidecar_status
// once at startup — a learned URL or terminal error still lands.
try {
  var invoke2 = window.__TAURI__ && window.__TAURI__.core && window.__TAURI__.core.invoke;
  if (typeof invoke2 === 'function') {
    invoke2('sidecar_status').then(function (st) {
      if (!st) return;
      if (st.url && !dashboardUrl) setDashboardUrl(String(st.url), 'status catch-up');
      else if (st.status === 'error' && st.detail) {
        stopPoll();
        markConn(false, 'sidecar error');
        say('sidecar failed: ' + st.detail + ' — board untouched. Restart the app; if it repeats, run the sidecar by hand: node <core> serve --port 0 --board <app-data>/board');
      }
    }).catch(function (e) {
      // A failed invoke must NEVER leave the static "no sidecar URL yet"
      // text with no explanation (installed-binary symptom, Oct 2026):
      // either the backend predates sidecar_status or the bridge is broken.
      say('sidecar status query failed (' + (e || 'invoke rejected') + ') — backend may predate sidecar_status; reinstall from the latest desktop-v* release.');
    });
  }
} catch (_) { /* static fallback: events only */ }

// 3. manual entry fallback for dev without Tauri.
if (!dashboardUrl) {
  say('no sidecar URL yet (pass ?dashboard=http://127.0.0.1:PORT, or run under Tauri).');
}

// Local environment toggle: OFF = remote-only. Under Tauri this invokes the
// `stop_sidecar` command (kills the child process); everywhere else it just
// detaches the iframe. Either way NO board state is deleted — stopping
// `serve` removes nothing under .crewbus/ (see docs/DESKTOP_SPIKE.md §4.4).
if (localEnv) {
  localEnv.addEventListener('change', function () {
    if (localEnv.checked) {
      say('Local environment ON — (re)start the sidecar via the supervisor, then set its URL.');
      return;
    }
    stopPoll();
    if (frame) frame.src = 'about:blank';
    markConn(false, 'remote-only: sidecar stopped by toggle');
    say('Remote-only mode: sidecar stopped. Board state NOT deleted.');
    try {
      var invoke = window.__TAURI__ && window.__TAURI__.core && window.__TAURI__.core.invoke;
      if (typeof invoke === 'function') invoke('stop_sidecar');
    } catch (_) { /* static fallback: detach only */ }
  });
}

// Pair window: Tauri `pair` webview when available, else a plain tab.
// The pair URL (crewbus://pair?...#abp-…) is handled in pair.js under
// fragment-secret hygiene (never logged, never persisted, #fragment only).
async function openPairWindow() {
  try {
    var invoke = window.__TAURI__ && window.__TAURI__.core && window.__TAURI__.core.invoke;
    if (typeof invoke === 'function') {
      await invoke('open_pair_window');
      return;
    }
  } catch (_) { }

  try {
    var ww = (window.__TAURI__ && window.__TAURI__.webviewWindow && window.__TAURI__.webviewWindow.WebviewWindow)
      || (window.__TAURI__ && window.__TAURI__.window && window.__TAURI__.window.WebviewWindow);
    if (ww && ww.getByLabel) {
      var existing = await ww.getByLabel('pair');
      if (existing) {
        if (existing.show) await existing.show();
        if (existing.unminimize) await existing.unminimize();
        if (existing.setFocus) await existing.setFocus();
        return;
      }
    }
  } catch (_) { }

  window.open('./pair.html', '_blank', 'width=420,height=560');
}

if (pairBtn) {
  pairBtn.addEventListener('click', function () {
    openPairWindow().catch(function () {});
  });
}

window.addEventListener('message', function (ev) {
  if (ev.data && ev.data.type === 'crewbus:open-pair') {
    openPairWindow().catch(function () {});
  }
});
