// CrewBus M4 pair-QR window — static ES module wired to the VENDORED
// runtime (src/vendor/runtime/, generated by `npm run vendor` from
// packages/client-runtime — never import out of root).
//
// Fragment-secret hygiene (packages/contracts/pairing.json, enforced by the
// runtime parsePairUrl imported below):
//   1. The pairing secret MUST come from the #fragment. Any secret-looking
//      query value (or secret-named query key) is REJECTED outright.
//   2. The full URL is NEVER logged, persisted, or embedded anywhere except
//      the in-memory QR render. Status lines print the env id only, with the
//      fragment stripped.
//   3. One-time link per device: Clear wipes the textarea + QR on demand;
//      the window holds no copy afterwards.
//
// Runs as plain static JS: browser globals only, `node --check` clean.

'use strict';

import { parsePairUrl } from './vendor/runtime/index.js';
import { renderQrSvg } from './vendor/qrcode.js';

var box = document.getElementById('pair-url');
var qr = document.getElementById('qr');
var qrWrap = document.getElementById('qr-wrap') || (qr ? qr.parentElement : null);
var msg = document.getElementById('msg');
var renderBtn = document.getElementById('pair-render');
var clearBtn = document.getElementById('pair-clear');

function say(t, isErr) {
  if (!msg) return;
  msg.textContent = t;
  msg.className = isErr ? 'warn' : 'ok';
}

function parsePairUrlSpike(raw) {
  var parsed = parsePairUrl(String(raw == null ? '' : raw).trim());
  return { env: parsed.env || '(unknown env)', pairToken: parsed.pairToken };
}

function describeForDisplay(u) {
  return String(u).split('#')[0];
}

function clearAll() {
  if (box) box.value = '';
  if (qrWrap) qrWrap.innerHTML = '<div id="qr" aria-label="pairing QR">QR code will appear here after rendering</div>';
  qr = document.getElementById('qr');
  say('');
}

if (renderBtn) {
  renderBtn.addEventListener('click', function () {
    var raw = box ? box.value : '';
    if (!raw.trim()) {
      say('paste a pair URL first', true);
      return;
    }
    var parsed;
    try {
      parsed = parsePairUrlSpike(raw);
    } catch (e) {
      say('rejected: ' + String((e && e.message) || e), true);
      return;
    }

    try {
      var svg = renderQrSvg(raw.trim(), {
        width: 200,
        margin: 1,
        color: { dark: '#f1f5f9', light: '#12151f' },
      });
      if (qrWrap) qrWrap.innerHTML = svg;
      say('QR code ready for ' + describeForDisplay(raw) + ' — scan with CrewBus Mobile.');
    } catch (err) {
      if (qr) qr.textContent = 'QR for ' + parsed.env + ' (' + parsed.pairToken.length + '-char secret)';
      say('QR render fallback: ' + String(err.message || err), true);
    }
  });
}

if (clearBtn) {
  clearBtn.addEventListener('click', clearAll);
}
