// CrewBus M4 pair-QR window — static ES module wired to the VENDORED
// runtime (src/vendor/runtime/, generated by `npm run vendor` from
// packages/client-runtime — never import out of root).
//
// Fragment-secret hygiene (packages/contracts/pairing.json, enforced by the
// runtime parsePairUrl imported below):
//   1. The pairing secret MUST come from the #fragment. Any secret-looking
//      query value (or secret-named query key) is REJECTED outright.
//   2. The full URL is NEVER logged, persisted, or embedded anywhere except
//      the in-memory QR render. Status lines print the env id only, with the
//      fragment stripped.
//   3. One-time link per device: Clear wipes the textarea + QR on demand;
//      the window holds no copy afterwards.
//
// Mint source: `node bin/crewbus.js serve --port 0 --pair-qrcode --from
// <admin>` (same mint + audit as `relay pair`) or `relay pair qr --from
// <admin>`. Exchange (swap abp-… once for abd-… with narrow-only scopes)
// happens on the device being paired (M5 mobile), not here.
//
// Runs as plain static JS: browser globals only, `node --check` clean.

'use strict';

import { parsePairUrl } from './vendor/runtime/index.js';

var box = document.getElementById('pair-url');
var qr = document.getElementById('qr');
var msg = document.getElementById('msg');
var renderBtn = document.getElementById('pair-render');
var clearBtn = document.getElementById('pair-clear');

function say(t, isErr) {
  if (!msg) return;
  msg.textContent = t;
  msg.className = isErr ? 'warn' : 'dim';
}

// Thin wrapper over the runtime parser (fragment-only secret, query
// rejected). Throws Error with the runtime message for the status line.
function parsePairUrlSpike(raw) {
  var parsed = parsePairUrl(String(raw == null ? '' : raw).trim());
  return { env: parsed.env || '(unknown env)', pairToken: parsed.pairToken };
}

function describeForDisplay(u) {
  // Strip the fragment BEFORE touching any status surface.
  return String(u).split('#')[0];
}

function clearAll() {
  if (box) box.value = '';
  if (qr) qr.textContent = 'QR placeholder — wire a renderer on the toolchain machine (M5)';
  say('');
}

if (renderBtn) {
  renderBtn.addEventListener('click', function () {
    var raw = box ? box.value : '';
    var parsed;
    try {
      parsed = parsePairUrlSpike(raw);
    } catch (e) {
      say('rejected: ' + String((e && e.message) || e), true);
      return;
    }
    // Placeholder render: show env + token length, NEVER the secret itself.
    // Toolchain machine replaces this block with a real QR encoder over the
    // full in-memory URL string (canvas, no network).
    if (qr) {
      qr.textContent = 'QR for ' + parsed.env + ' (' + parsed.pairToken.length + '-char fragment secret, hidden)';
    }
    say('pairing URL accepted for ' + describeForDisplay(raw) + ' — secret kept in memory only.');
  });
}

if (clearBtn) {
  clearBtn.addEventListener('click', clearAll);
}
