// CrewBus vendor-runtime: copy the Metro/Tauri-safe client-runtime core
// into the app shells and point the app imports at the vendored copies.
//
// Why: Metro only bundles inside the app root (apps/mobile) and the Tauri
// static shell serves src/ only (apps/desktop/src), so out-of-root imports
// like `../../../packages/client-runtime/index.js` can never resolve in a
// built app. This script copies every runtime module EXCEPT the Node-only
// adapter (`node-adapter.js` imports node:* and stays Node-side) into
// `src/vendor/runtime/` of each app, then rewrites the app import
// specifiers to the vendored paths (mechanical prefix change only —
// comments and prose are never touched).
//
// Run: `node scripts/vendor-runtime.mjs` (from the repo root) or
// `npm run vendor`. Re-run after ANY change to packages/client-runtime/.
// Idempotent: re-running produces byte-identical output (rewrites are a
// fixpoint — vendored specifiers no longer match the rewrite pattern).
// Plain node, zero dependencies.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'packages', 'client-runtime');
const HEADER = '// DO NOT EDIT — generated by scripts/vendor-runtime.mjs from packages/client-runtime/\n';
// The runtime loads its scope vocabulary from this contract path RELATIVE
// TO auth.js (`../contracts/pairing.json`). The same relative layout is
// reproduced under each vendor dir, so the vendored auth.js resolves its
// vocabulary the same way on Node (tests) and, where the bundler/static
// server allows, on-device. Where it cannot resolve (Metro), the module
// falls back to caller-supplied knownScopes — see auth.js.
const CONTRACT_SRC = path.join(ROOT, 'packages', 'contracts', 'pairing.json');
const CONTRACT_DEST_SUB = path.join('contracts', 'pairing.json');

// node-adapter.js stays Node-side only (it imports node:* modules, so it
// can never bundle into Metro or the Tauri static shell).
const RUNTIME_FILES = fs.readdirSync(SRC_DIR)
  .filter((f) => f.endsWith('.js') && f !== 'node-adapter.js')
  .sort();

const APPS = [
  { name: 'mobile', dir: path.join(ROOT, 'apps', 'mobile'), roots: ['App.js', 'src', 'api'] },
  { name: 'desktop', dir: path.join(ROOT, 'apps', 'desktop'), roots: ['src'] },
];

const JS_EXT = new Set(['.js', '.jsx']);
// Only import specifiers are rewritten: `from '...'` / `import('...')` on
// one line. Prose mentions of packages/client-runtime are left alone.
const SPEC_RE = /(from\s+|import\s*\(\s*)(['"])((?:\.\.\/)+packages\/client-runtime\/([\w.\-]+\.js))\2/g;

function walkJs(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'vendor') continue; // never rewrite generated copies
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) walkJs(abs, out);
    else if (entry.isFile() && JS_EXT.has(path.extname(entry.name))) out.push(abs);
  }
  return out;
}

// Replaces the upstream dynamic contract-load block in auth.js (from
// `const PAIRING_CONTRACT_SPEC = ` through the closing of its try/catch,
// right before the `// Native shells...` comment) with statically inlined
// vocabulary read from the contract copy above. Throws when the block is
// not found (upstream refactored) — re-vendor must never silently ship
// the unparseable form to Metro.
function metroTransformAuth(src, appName) {
  const startMarker = 'const PAIRING_CONTRACT_SPEC = ';
  const endMarker = '\n// Native shells that cannot resolve';
  const start = src.indexOf(startMarker);
  const end = src.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`vendor: auth.js upstream loader block not found — update metroTransformAuth (app ${appName})`);
  }
  const contract = JSON.parse(fs.readFileSync(path.join(ROOT, 'packages', 'contracts', 'pairing.json'), 'utf8'));
  if (!Array.isArray(contract.scopes) || contract.scopes.length === 0 || typeof contract.version !== 'number') {
    throw new Error('vendor: pairing.json scopes/version malformed');
  }
  const listed = contract.scopes.map((s) => `  '${s}',`).join('\n');
  const replacement =
    `// Inlined from src/vendor/contracts/pairing.json (frozen-M0) by\n` +
    `// scripts/vendor-runtime.mjs — Metro/Hermes cannot parse the upstream\n` +
    `// dynamic JSON import, so vendoring resolves it statically. Keep in sync\n` +
    `// via re-vendor (check.mjs asserts scope + version parity).\n` +
    `const VENDORED_SCOPES = Object.freeze([\n${listed}\n]);\n` +
    `const VENDORED_CONTRACT_VERSION = ${contract.version};\n` +
    `\n` +
    `let knownScopes = VENDORED_SCOPES;\n` +
    `export let PAIRING_CONTRACT_VERSION = VENDORED_CONTRACT_VERSION;\n`;
  return src.slice(0, start) + replacement + src.slice(end + 1);
}

function toPosix(p) {
  return p.split(path.sep).join('/');
}

let copied = 0;
let rewrote = 0;

for (const app of APPS) {
  const vendorDir = path.join(app.dir, 'src', 'vendor', 'runtime');
  fs.mkdirSync(vendorDir, { recursive: true });

  // Scope contract at the same relative layout auth.js expects
  // (`../contracts/pairing.json` from the runtime dir). JSON is copied
  // verbatim (no header comment — it must stay parseable JSON).
  const contractDest = path.join(app.dir, 'src', 'vendor', CONTRACT_DEST_SUB);
  fs.mkdirSync(path.dirname(contractDest), { recursive: true });
  {
    const src = fs.readFileSync(CONTRACT_SRC, 'utf8');
    JSON.parse(src); // fail loud now, not on a toolchain machine
    const prev = fs.existsSync(contractDest) ? fs.readFileSync(contractDest, 'utf8') : null;
    if (prev !== src) {
      fs.writeFileSync(contractDest, src);
      copied += 1;
      console.log(`vendor: ${app.name} src/vendor/contracts/pairing.json (updated)`);
    }
  }

  for (const file of RUNTIME_FILES) {
    const src = fs.readFileSync(path.join(SRC_DIR, file), 'utf8');
    const dest = path.join(vendorDir, file);
    // Metro-safe transform for auth.js (check.mjs §8 asserts the result):
    // Metro/Hermes cannot even PARSE `await import(x, { with: {...} })`
    // (transform-time failure) and Hermes has no top-level await, so the
    // vendored copy resolves the contract load statically — scopes inlined
    // from the pairing.json copied above. Fail loud if the upstream loader
    // block moves, so divergence ships never silently.
    let body = src;
    if (file === 'auth.js') body = metroTransformAuth(src, app.name);
    const next = HEADER + body;
    const prev = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
    if (prev !== next) {
      fs.writeFileSync(dest, next);
      copied += 1;
      console.log(`vendor: ${app.name} src/vendor/runtime/${file} (updated)`);
    }
  }

  const targets = [];
  for (const root of app.roots) {
    const abs = path.join(app.dir, root);
    if (!fs.existsSync(abs)) continue;
    if (fs.statSync(abs).isDirectory()) walkJs(abs, targets);
    else if (JS_EXT.has(path.extname(abs))) targets.push(abs);
  }

  for (const file of targets) {
    const text = fs.readFileSync(file, 'utf8');
    const next = text.replace(SPEC_RE, (m, lead, quote, _old, leaf) => {
      const rel = toPosix(path.relative(path.dirname(file), path.join(vendorDir, leaf)));
      const spec = rel.startsWith('.') ? rel : `./${rel}`;
      return `${lead}${quote}${spec}${quote}`;
    });
    if (next !== text) {
      fs.writeFileSync(file, next);
      rewrote += 1;
      console.log(`vendor: rewrote specifiers in ${toPosix(path.relative(ROOT, file))}`);
    }
  }
}

console.log(`vendor-runtime: ${RUNTIME_FILES.length} modules x ${APPS.length} apps, ${copied} file(s) written, ${rewrote} app file(s) re-pointed`);
